server:
  port: 8000
spring:
  application:
#    服务名称
    name: cloud-order-service


eureka:
  #声明它是一个eureka的客户端
  client:
    #表示是否将自己注册进eurekaServer，默认为ture
    register-with-eureka: true
    #表示是否从EurekaServer抓取已有的注册信息，默认为true，单点无所谓，集群必须设为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #表示客户端注册的eurekaServer的地址
    service-url:
      defaultZone: http://localhost:7001/eureka