server:
  port: 8088
  # Let NetworkManager manage all devices on this system
  network:
    ethernets:
      ens33:                  # 配置的网卡名称
        dhcp4: no           # 关闭dhcp4
        dhcp6: no           # 关闭dhcp6
        addresses: [192.168.0.120/24]       # 设置本机IP地址及掩码
        gateway4: 192.168.0.1               # 设置网关
        nameservers:
          addresses: [114.114.114.114, 8.8.8.8,192.168.120.2,127.0.0.53]       # 设置DNS
    version: 2
    renderer: NetworkManager