#服务端口
server:
  port: 8001

#  服务配置
spring:
  application:
    name: cloud-payment-service
  datasource:
    #    当前数据库操作 类型
    type: com.alibaba.druid.pool.DruidDataSource
    #    mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dev
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.diwang.springcloud.entities
#    它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔（value的值一定要是包的全）
